- .github/workflows/android-master-ci.yml
- README.md
- sdk/src/test/java/com/karhoo/sdk/api/service/trips/BookTripInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/trips/CancelTripInteractorTest.kt
[MOB-2755](https://karhoo.atlassian.net/browse/MOB-2755)
Add Master Branch workflow
> Add master branch workflow and fix unit tests

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/QuotesIntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/QuotesV2IntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/SDKInitialiserIntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/KarhooQuotesService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/QuotesService.kt
[MOB-2854](https://karhoo.atlassian.net/browse/MOB-2854)
Integrate Quotes V2 and add integration tests
> MOB-2867 - 

- build.gradle
- sdk/build.gradle
[MOB-2884](https://karhoo.atlassian.net/browse/MOB-2884)
Update dagger libs to 2.28.3
N/a
> MOB-2884 - Dagger version update

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/TestData.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/FleetInfo.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/QuoteV2.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/KarhooQuotesService.kt
[MOB-2881](https://karhoo.atlassian.net/browse/MOB-2881)
Removed email and qta_high from QuotesV2
- x] New feature 
> Mob 2881 remove email from fleet info

- sdk/build.gradle
[MOB-XXXX]
Version update to fix bintray issue
> MOB-XXXX - Version update

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/model/MeetingPoint.kt
[MOB-XXXX]
Set default meeting point type to NOT_SET instead of null
N/a
> MOB-XXXX - Set default meeting point type to NOT_SET

- sdk/src/main/java/com/karhoo/sdk/api/model/Provider.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractorTest.kt
[MOB-2708](https://karhoo.atlassian.net/browse/MOB-2708)
Created Get Provider Interactor + success and failure tests
> Mob 2708 provider interactor

- sdk/src/androidTest/java/com/karhoo/sdk/api/PaymentProviderIntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/KarhooPaymentsService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentsService.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/KarhooPaymentsServiceTest.kt
[MOB-2708](https://karhoo.atlassian.net/browse/MOB-2708)
Complete integration of Payment Provider endpoint
> Mob 2708 services payment provider

- .circleci/config.yml
MOB-XXXX
Enable CircleCI runs
N/a
> MOB-XXXX - Enable CircleCI runs

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/PaymentProvider.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Provider.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractorTest.kt
[MOB-2713](https://karhoo.atlassian.net/browse/MOB-2713)
Update Provider model wrap in Provider and make LoyaltyProgramme optionaal
N/a
> MOB-2713 - Fix Provider model

- .circleci/config.yml
- build.gradle
MOB-XXXX
Changes to use UseContainerSupport
N/a
> MOB-XXXX - Fix circleci config

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/KarhooUserManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/KarhooUserStore.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/UserManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/UserStore.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/KarhooPaymentsService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/user/UserLoginInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/user/UserLoginInteractorTest.kt
[MOB-2909](https://karhoo.atlassian.net/browse/MOB-2909)
Make call to retrieve the payment provider on successful login
> MOB-2909 - Payment provider call on login

- sdk/src/main/java/com/karhoo/sdk/api/model/Constants.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/adyen/AdyenAction.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/adyen/AdyenBillingAddress.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/adyen/AdyenData.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/adyen/AdyenPaymentDetail.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/adyen/AdyenPayments.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/adyen/AdyenRedirect.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/request/AdyenPaymentMethodsRequest.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/header/KarhooHeadersTest.kt
[MOB-2710](https://karhoo.atlassian.net/browse/MOB-2710)
> MOB-2710 - Additional Adyen payments request/response elements

- sdk/build.gradle
[MOB-2901](https://karhoo.atlassian.net/browse/MOB-2901)
Released version 1.0.12 of the SDK and version 1.0.12.01092020 of the Canary edition of the SDK
> [MOB-2901] Release 1.0.12

- sdk/build.gradle
> [MOB-XXXX] Release 1.0.35

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/AdyenPaymentMethodsIntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/AdyenPaymentsIntegrationTest.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenPaymentMethodsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenPaymentsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/KarhooPaymentsService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentsService.kt
- sdk/src/main/java/com/karhoo/sdk/di/NetworkModule.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/AdyenPaymentMethodsInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/AdyenPaymentsInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/KarhooPaymentsServiceTest.kt
[MOB-2715](https://karhoo.atlassian.net/browse/MOB-2715)
Updates to fix the requests and responses to enable Drop In integration
N/a
> Mob 2715 fix request response

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
[MOB-2716](https://karhoo.atlassian.net/browse/MOB-2716)
Fix the payment details endpoint
N/a
> Fix payments-details endpoint

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/AdyenPaymentsDetailsIntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/CardType.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
[MOB-2716](https://karhoo.atlassian.net/browse/MOB-2716)
Change CardType to handle Adyen and rename endpoints
N/a
> MOB-2716 - Adyen card type fix

- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/header/KarhooHeaders.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/trips/BookTripInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/adapter/SealedCoroutineCallAdapterFactoryTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/header/KarhooHeadersTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/trips/BookTripInteractorTest.kt
[MOB-2445](https://karhoo.atlassian.net/browse/MOB-2445)
Updated BookingInteractor to allow the payment of a trip by invoice.
Depending on the presence of a Nonce or not, a different endpoint will be called.
> Update of BookingInteractor

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/AdyenPaymentsDetailsIntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/AdyenPaymentsIntegrationTest.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenPaymentsDetailsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenPaymentsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/KarhooPaymentsService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentsService.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/AdyenPaymentsDetailsInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/AdyenPaymentsInteractorTest.kt
[MOB-2717](https://karhoo.atlassian.net/browse/MOB-2717)
Return JSONObject response instead of String for Adyen payments and payments-details endpoints
> MOB-2717 - Return JSONObject response instead of String

- sdk/build.gradle
> Bumping canary version for UISDK

- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/user/KarhooUserService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/user/UserService.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/user/KarhooUserServiceTest.kt
[MOB-2978](https://karhoo.atlassian.net/browse/MOB-2978)
Revoke refresh token on logout called.
> [MOB-2978] Auth revoke refresh token

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractorTest.kt
[MOB-3027](https://karhoo.atlassian.net/browse/MOB-3027)
Only make the call to retrieve the payment provider if there is an organisation for the user
N/a
> MOB-3027 - Fix guest checkout payment provider call crash

- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/AvailabilityVehicle.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/QuoteVehicle.kt
[MOB-3047](https://karhoo.atlassian.net/browse/MOB-3047)
Updated Quotes and Availability response to contain Vehicle tags and types
> [MOB-3047] Vehicle types and tags

- sdk/build.gradle
[MOB-3032](https://karhoo.atlassian.net/browse/MOB-3032)
Release candidate for 1.1.0
N/a
> MOB-3032 - 1.1.0 release candidate

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/network/request/TripBooking.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/trips/BookTripInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/trips/KarhooTripsServiceTest.kt
[MOB-3070](https://karhoo.atlassian.net/browse/MOB-3070)
Add meta field to TripBooking
N/a
> MOB-3070 - Add TripBooking meta field

- sdk/src/main/java/com/karhoo/sdk/api/network/request/TripCancellation.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/trips/CancelTripInteractor.kt
[MOB-3055](https://karhoo.atlassian.net/browse/MOB-3055)
Add explanation to the cancellation request model
> Mob 3055 update cancellationrequest

- build.gradle
- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/network/client/RequestInterceptor.kt
[MOB-3040](https://karhoo.atlassian.net/browse/MOB-3040)
Everything passes, works as expected. Tests pass, UISDK passes and works as expected.
> [MOB-3040] Update to Kotlin 1.4.21

- sdk/build.gradle
[MOB-3078](https://karhoo.atlassian.net/browse/MOB-3078)
Just a simple fix. All tests pass, NSDK working as expected.
> [MOB-3078] update Parcelize usage

- sdk/src/androidTest/java/com/karhoo/sdk/api/LoyaltyConversionIntregrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/LoyaltyConversion.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/LoyaltyRates.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/KarhooLoyaltyService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/LoyaltyBalanceInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/LoyaltyConversionInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/LoyaltyService.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/loyalty/KarhooLoyaltyServiceTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/loyalty/LoyaltyBalanceInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/loyalty/LoyaltyConversionInteractorTest.kt
[MOB-3052](https://karhoo.atlassian.net/browse/MOB-3052)
> [MOB-3052] Loyalty Conversion 

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- sdk/build.gradle
[MOB-3097](https://karhoo.atlassian.net/browse/MOB-3097)
Updated some versions
> [MOB-3097] Gradle version, Jacoco gone.

- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/TestData.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/QuoteList.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/QuoteStatus.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Vehicles.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/QuotesInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/quotes/QuotesInteractorTest.kt
[MOB-3132](https://karhoo.atlassian.net/browse/MOB-3132)
> [MOB-3132] Add validity and status to QuoteList object

- sdk/.gitignore
- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/model/QuoteList.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/QuoteStatus.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Vehicles.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/request/Passengers.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/QuotesInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/quotes/QuotesInteractorTest.kt
[MOB-3132](https://karhoo.atlassian.net/browse/MOB-3132)
Remove hardcoded value for the quoteStatus
> Remove hardcoded value for the quoteStatus

- .github/delete-merged-branch-config.yml
- README.md
- sdk/build.gradle
[MOB-3151](https://karhoo.atlassian.net/browse/MOB-3151)
Rebase to master
N/a
> Rebase to master

- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/trips/CancellationFeeInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/trips/CancellationFeeInteractorTest.kt
[MOB-3182](https://karhoo.atlassian.net/browse/MOB-3182)
> [MOB-3182] Add functionality for fees with guests

- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/ServiceAgreements.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/ServiceCancellation.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/ServiceWaiting.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/TripInfo.kt
[MOB-3189](https://karhoo.atlassian.net/browse/MOB-3189)
> [MOB-3189] Cancellation SLA booking models

- sdk/src/androidTest/java/com/karhoo/sdk/api/CancellationFeeIntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/TestData.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Quote.kt
[MOB-3191](https://karhoo.atlassian.net/browse/MOB-3191)
> [MOB-3191] Quotes Cancellation SLA

- gradle.properties
- sdk/build.gradle
> [MOB-XXXX] Canary 1.2.2 release

- sdk/src/main/java/com/karhoo/sdk/api/KarhooError.kt
- sdk/src/test/java/com/karhoo/sdk/api/KarhooErrorTest.kt
[MOB-3201](https://karhoo.atlassian.net/browse/MOB-3201)
Add support for custom errors
> Add support for custom errors

- sdk/build.gradle
[MOB-3202](https://karhoo.atlassian.net/browse/MOB-3202)
Canary release for custom errors
> Canary Release 1.2.2.03032021-1 custom errors

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/model/FleetInfo.kt
[MOB-3209](https://karhoo.atlassian.net/browse/MOB-3209)
Update fleet info model
> Update fleet info model

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/KarhooUserManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/KarhooUserStore.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/UserManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/UserStore.kt
- sdk/src/test/java/com/karhoo/sdk/api/datastore/user/KarhooUserManagerTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/datastore/user/UserStoreTest.kt
[MOB-3187](https://karhoo.atlassian.net/browse/MOB-3187)
Add methods to enable deletion of saved payment info
N/a
> MOB-3187 - Enable clearing of saved payment info

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/QuotesIntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Fleet.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/FleetInfo.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Quote.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/quotes/VerifyQuoteInteractorTest.kt
[MOB-3209](https://karhoo.atlassian.net/browse/MOB-3209)
Add Fleet model and update the Quote model
> Add Fleet model and update the Quote model

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/QuotesInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/quotes/QuotesInteractorTest.kt
[MOB-3214](https://karhoo.atlassian.net/browse/MOB-3214)
Clear quote id when a quote list with status of complete is returned
N/a
> Clear quoteId if quote status is completed

- sdk/build.gradle
[MOB-3213](https://karhoo.atlassian.net/browse/MOB-3213)
Migrate to using Jitpack instead of bintray as JCenter is being sunsetted.
N/a
> MOB-3213 - Jitpack migration

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
[MOB-3215](https://karhoo.atlassian.net/browse/MOB-3215)
> [MOB-3215] Release candidate 1.3.0-rc01 + polling fix

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
[MOB-3215](https://karhoo.atlassian.net/browse/MOB-3215)
> [MOB-3215] Release 1.3.0 tested

- sdk/src/main/java/com/karhoo/sdk/api/model/TripInfo.kt
[MOB-3372](https://karhoo.atlassian.net/browse/MOB-3372)
Add meta dictionary to the TripInfo
> Add meta dictionary to the TripInfo

- sdk/build.gradle
[MOB-3388](https://karhoo.atlassian.net/browse/MOB-3388)
> Network SDK Release 1.4.0

- sdk/build.gradle
[MOB-3255](https://karhoo.atlassian.net/browse/MOB-3255)
> target 29 to 30, compile version 29 to 30

- sdk/src/androidTest/java/com/karhoo/sdk/api/AuthLoginIntegrationTest.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthLoginWithTokenInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/KarhooAuthService.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/AuthLoginWithTokenInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/KarhooAuthServiceTest.kt
[MOB-3432](https://karhoo.atlassian.net/browse/MOB-3432)
Add "login with KH credentials" to Network SDK
> MOB-3432 Add "login with karhoo credentials" (token) to Network SDK

- build.gradle
- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/AuthLoginIntegrationTest.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthLoginWithTokenInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/KarhooAuthService.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/AuthLoginWithTokenInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/KarhooAuthServiceTest.kt
[MOB-3447](https://karhoo.atlassian.net/browse/MOB-3447)
> MOB-3447 post release 1.4.1

- build.gradle
- sdk/build.gradle
[MOB-3447](https://karhoo.atlassian.net/browse/MOB-3447)
> MOB-3447 release 1.4.1

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/KarhooError.kt
> Release 1.4.3

- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/KarhooQuotesService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/QuotesInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/QuotesService.kt
[MOB-3688](https://karhoo.atlassian.net/browse/MOB-3688)
Overloaded a few methods with locale
> Mob 3688 add locale parameter to retrieve quote list endpoint

- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/KarhooUserManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/KarhooUserStore.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/UserManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/UserStore.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/LoyaltyProgramme.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/PaymentProvider.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Provider.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractorTest.kt
[MOB-3656](https://karhoo.atlassian.net/browse/MOB-3656)
MOB-3656 Corrected loyalty programme pojo 2
> MOB-3656 Corrected loyalty programme pojo 2

- sdk/build.gradle
[MOB-3748](https://karhoo.atlassian.net/browse/MOB-3748)
Android Network SDK Release v1.4.4/ UI SDK1.5.1
> MOB-3748: Release 1.4.4 [develop]

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/KarhooUserManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Provider.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/adyen/AdyenClientKey.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenClientKeyInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenPaymentMethodsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenPaymentsDetailsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenPaymentsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenPublicKeyInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/KarhooPaymentsService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentsService.kt
[MOB-4025](https://karhoo.atlassian.net/browse/MOB-4025)
SDK Release
> MOB-4025 post release 1.4.5

- sdk/build.gradle
[MOB-4025](https://karhoo.atlassian.net/browse/MOB-4025)
NSDK Release
> MOB-4025 Release new Android SDK versions (Network and UI)

- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractorTest.kt
[MOB-4087](https://karhoo.atlassian.net/browse/MOB-4087)
MOB-4087 Make the NSDK payment provider agnostic
> MOB-4087 Make the NSDK payment provider agnostic

- sdk/src/main/java/com/karhoo/sdk/analytics/Payloader.kt
[MOB-4080](https://karhoo.atlassian.net/browse/MOB-4080)
> MOB-4080 [Analytics] Add logs on the Payment failed event

- sdk/build.gradle
[MOB-4141](https://karhoo.atlassian.net/browse/MOB-4141)
> MOB-4141 Release NSDK and UISDK

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/analytics/Payloader.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractorTest.kt
[MOB-4141](https://karhoo.atlassian.net/browse/MOB-4141)
SDK Release
> MOB-4141 post release 1 4 6

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/analytics/Event.kt
- sdk/src/main/java/com/karhoo/sdk/analytics/Payloader.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
Fix issue with user id not existing at first install
Fix issue with user id not existing at first install
> Fix issue with user id not existing at first install

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/analytics/Event.kt
- sdk/src/main/java/com/karhoo/sdk/analytics/Payloader.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
[MOB-4173](https://karhoo.atlassian.net/browse/MOB-4173)
MOB-4173 Post Release 1.4.7
> MOB-4173 post release 1.4.7

- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/QuotesInteractor.kt
[MOB-4193](https://karhoo.atlassian.net/browse/MOB-4193)
> MOB-4193   Some addresses results in K0002 in new quote list

- sdk/build.gradle
[MOB-4259](https://karhoo.atlassian.net/browse/MOB-4259)
Release new Android Network SDK without Segment dependency
> MOB-4259 Release new Android Network SDK without Segment dependency

- sdk/src/main/java/com/karhoo/sdk/analytics/Payloader.kt
[MOB-4222](https://karhoo.atlassian.net/browse/MOB-4222)
> MOB-4222   Align analytics Keys (in UI and Network SDK) between platforms

- default-detekt-config.yml
- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/QuoteImagesRuleListIntegrationTest.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/ServerRobot.kt
- sdk/src/main/java/com/karhoo/sdk/analytics/Event.kt
- sdk/src/main/java/com/karhoo/sdk/analytics/Payloader.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/QuoteVehicle.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/VehicleMapping.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/VehicleMappings.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/adapter/SealedCoroutineCallAdapterFactory.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/RequestInterceptor.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/response/Resource.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/KarhooQuotesService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/QuotesInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/QuotesService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/quotes/VehicleMappingsInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/SDKTestConfig.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/adapter/SealedCoroutineCallAdapterFactoryTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/quotes/VehicleMappingsInteractorTest.kt
[MOB-4216](https://karhoo.atlassian.net/browse/MOB-4216)
MOB-4216 post release 1.5.0
> MOB-4216 post release 1.5.0

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/PaymentProviderInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/SDKTestConfig.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/adapter/SealedCoroutineCallAdapterFactoryTest.kt
[MOB-4216](https://karhoo.atlassian.net/browse/MOB-4216)
MOB-4216 Release Network SDK Android v1.5.0
> MOB-4216 Release Network SDK Android v1.5.0

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/TestData.kt
- sdk/src/main/java/com/karhoo/sdk/api/KarhooSDKConfiguration.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/credentials/CredentialsManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/credentials/KarhooCredentialsManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Credentials.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthLoginWithTokenInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/common/BaseCallInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/common/BasePollCallInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/common/InteractorConstants.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/user/UserLoginInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/datastore/user/KarhooCredentialsManagerTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/datastore/user/KarhooUserManagerTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/interactor/BaseCallInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/interactor/BaseInteractorMock.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/AuthLoginWithTokenInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentNonceInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/user/UserLoginInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/testrunner/UnitTestSDKConfig.kt
[MOB-4134](https://karhoo.atlassian.net/browse/MOB-4134)
MOB-4134 Proactively refresh token in the network SDK
> MOB-4134 Proactively refresh token in the network SDK

- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/RequestInterceptor.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/adapter/SealedCoroutineCallAdapterFactoryTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/quotes/VehicleMappingsInteractorTest.kt
[MOB-4348](https://karhoo.atlassian.net/browse/MOB-4348)
> Mob 4348 Fleet logos appear instead of vehicle images

- sdk/build.gradle
> Release 1.5.1

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/RequestInterceptor.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/adapter/SealedCoroutineCallAdapterFactoryTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/quotes/VehicleMappingsInteractorTest.kt
> Post release 1 5 1

- sdk/build.gradle
[MOB-4356](https://karhoo.atlassian.net/browse/MOB-4356)
> MOB-4356 Bumped version

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/service/common/RequestsQueue.kt
> MOB-4125 Removed poll delay 

- sdk/build.gradle
> Release 1.6.0

- sdk/build.gradle
- sdk/src/androidTest/java/com/karhoo/sdk/api/testrunner/TestSDKConfig.kt
- sdk/src/androidTest/java/com/karhoo/sdk/api/util/TestData.kt
- sdk/src/main/java/com/karhoo/sdk/api/KarhooError.kt
- sdk/src/main/java/com/karhoo/sdk/api/KarhooSDKConfiguration.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/credentials/CredentialsManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/credentials/KarhooCredentialsManager.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/Credentials.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthLoginWithTokenInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/common/BaseCallInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/common/BasePollCallInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/common/InteractorConstants.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/common/InteractorContants.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/common/RequestsQueue.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/user/UserLoginInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/datastore/user/KarhooCredentialsManagerTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/datastore/user/KarhooUserManagerTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/interactor/BaseCallInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/interactor/BaseInteractorMock.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/interactor/BasePollCallInteractorMock.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/interactor/BasePollCallInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/auth/AuthLoginWithTokenInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/PaymentNonceInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/user/UserLoginInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/testrunner/UnitTestSDKConfig.kt
> Mob 4372 post release 1 6 0

- sdk/build.gradle
- sdk/src/main/java/com/karhoo/sdk/api/model/LocationInfo.kt
[MOB-4437](https://karhoo.atlassian.net/browse/MOB-4437)
MOB-4437 Made the address public in the locationinfo
> MOB-4437 Made the address public in the locationinfo

- sdk/src/main/java/com/karhoo/sdk/analytics/Payloader.kt
- sdk/src/main/java/com/karhoo/sdk/api/KarhooSDKConfiguration.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/KarhooUserStore.kt
- sdk/src/main/java/com/karhoo/sdk/api/datastore/user/UserStore.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/common/RequestsQueue.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/payments/AdyenPublicKeyInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/user/UserLoginInteractor.kt
- sdk/src/test/java/com/karhoo/sdk/api/datastore/user/UserStoreTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/network/interactor/BaseCallInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/loyalty/KarhooLoyaltyServiceTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/payments/AdyenPublicKeyInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/quotes/QuotesInteractorTest.kt
- sdk/src/test/java/com/karhoo/sdk/api/service/user/KarhooUserServiceTest.kt
[MOB-4337](https://karhoo.atlassian.net/browse/MOB-4337)
> removed unused imports

- build.gradle
[MOB-4506](https://karhoo.atlassian.net/browse/MOB-4506)
> MOB-4506 Remove jcenter()

- sdk/build.gradle
[MOB-4500](https://karhoo.atlassian.net/browse/MOB-4500)
[MOB-4500]: https://karhoo.atlassian.net/browse/MOB-4500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 1.6.2

- sdk/build.gradle
[MOB-4490](https://karhoo.atlassian.net/browse/MOB-4490)
[MOB-4490]: https://karhoo.atlassian.net/browse/MOB-4490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4490 Test out trunk migration

- sdk/build.gradle
[MOB-4591](https://karhoo.atlassian.net/browse/MOB-4591)
[MOB-4591]: https://karhoo.atlassian.net/browse/MOB-4591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4591 Release 1.6.3

- sdk/src/main/java/com/karhoo/sdk/api/model/QuoteVehicle.kt
[MOB-4391](https://karhoo.atlassian.net/browse/MOB-4391)
MOB-4391 [Quote] Add standard as vehicle category filters
[MOB-4391]: https://karhoo.atlassian.net/browse/MOB-4391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4391 [Quote] Add standard as vehicle category filters

- CODEOWNERS
[MOB-4595](https://karhoo.atlassian.net/browse/MOB-4595)
[MOB-4595]: https://karhoo.atlassian.net/browse/MOB-4595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4595 | Added CODEOWNERS file

- sdk/build.gradle
[MOB-4730](https://karhoo.atlassian.net/browse/MOB-4730)
[MOB-4730]: https://karhoo.atlassian.net/browse/MOB-4730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4730 Release 1.8.0

- sdk/src/main/java/com/karhoo/sdk/api/KarhooApi.kt
- sdk/src/main/java/com/karhoo/sdk/api/KarhooService.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/LoggingEvent.kt
- sdk/src/main/java/com/karhoo/sdk/api/model/LoggingResponse.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
- sdk/src/main/java/com/karhoo/sdk/api/network/request/LoggingRequest.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/logging/EventLoggerInteractor.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/logging/EventLoggerService.kt
- sdk/src/main/java/com/karhoo/sdk/api/service/logging/KarhooEventLoggerService.kt
- sdk/src/main/java/com/karhoo/sdk/di/ApplicationComponent.kt
[MOB-4732](https://karhoo.atlassian.net/browse/MOB-4732)
MOB-4732 Research logging mechanism for UI SDK
[MOB-4732]: https://karhoo.atlassian.net/browse/MOB-4732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4732 Research logging mechanism for UI SDK

- sdk/src/main/java/com/karhoo/sdk/api/model/FeatureFlag.kt
[MOB-4775](https://karhoo.atlassian.net/browse/MOB-4775)
[MOB-4775]: https://karhoo.atlassian.net/browse/MOB-4775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4775 Merge FeatureFlags & LoyaltyFeatureFlags

- sdk/src/main/java/com/karhoo/sdk/api/KarhooError.kt
[MOB-4841](https://karhoo.atlassian.net/browse/MOB-4841)
[MOB-4841]: https://karhoo.atlassian.net/browse/MOB-4841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4841 Research Invalid request

- build.gradle
- sdk/build.gradle
[MOB-4904](https://karhoo.atlassian.net/browse/MOB-4904)
[MOB-4904]: https://karhoo.atlassian.net/browse/MOB-4904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4904 kotlin update
